# Generated by Django 3.0.4 on 2020-07-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_balance', models.IntegerField()),
                ('new_balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_No', models.IntegerField(unique=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('month', models.CharField(default=0, max_length=200)),
                ('year', models.CharField(default=0, max_length=200)),
                ('income', models.CharField(default=0, max_length=200)),
                ('expenditure', models.CharField(default=0, max_length=200)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
