# Generated by Django 3.0.4 on 2020-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='new_balance',
        ),
        migrations.AlterField(
            model_name='balance',
            name='old_balance',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
